name: recipe_ai_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.3 
  http: ^1.2.1 
  path: any
  path_provider: ^2.0.2
  flutter_markdown: ^0.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
